# Constants
BUFFER_SIZE = 32
INITIAL_SIZE = 1024
CLIENT_ROOT_PATH = "client_files"
STORAGE_SERVER_ROOT_PATH = "sserver_files"
NAMING_SERVER_IP = "localhost"
NAMING_SERVER_PORT = 8800
STORAGE_SERVER_PORT = 8801
PING_SERVERS_SECONDS = 20

# Codes

ERR_FILE_NOT_EXIST = 1
ERR_FILE_DIR_NOT_EXIST = 2
ERR_DIR_NOT_EXIST = 3
ERR_DIR_EXISTS = 20
ERR_FILE_EXISTS = 21

CODE_OK = 4
CODE_FILE_NOT_EXIST = 5
CODE_FILE_ALREADY_EXIST = 6
CODE_DIRECTORY_NOT_EXIST = 7
CODE_DIRECTORY_ALREADY_EXIST = 8

DIR_OPEN_OK = 9
DIR_OPEN_NOT_EXIST = 10
DIR_OPEN_PREV = 11
DIR_OPEN_ROOT = 12

DIR_DELETE_NOT_EXIST = 13
DIR_DELETE_HAS_FILES = 14
DIR_DELETE_OK = 15

FILE_RECEIVE_CONFIRMATION_TO_NAMING = 16
FILE_NOT_EXIST_ON_STORAGE_SERVER = 17
FILE_EXISTS_ON_STORAGE_SERVER = 18
FILE_EXISTS = 19
NOT_FORCE = 22
CMD_PING_FROM_STORAGE = 23
