# Constants
BUFFER_SIZE = 32
INITIAL_SIZE = 1024
STORAGE_SERVER_ROOT_PATH = "sserver_files"
NAMING_SERVER_IP = "localhost"
STORAGE_SERVER_PORT = 8801
PING_SERVERS_SECONDS = 20
NAMING_SERVER_PORT = 8800  # 555-35-35
# Codes

ERR_PATH_NOT_CORRECT = 1
ERR_FILE_DIR_NOT_EXIST = 2
ERR_DIR_EXISTS = 20
ERR_FILE_EXISTS = 21
CODE_OK = 4

